# Generated by Django 4.1.3 on 2022-12-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=100),
        ),
    ]
